/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "code16.sharp.home": [
        {
            "name": "globalFilter"
        }
    ],
    "code16.sharp.dashboard": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.dashboard.filters.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true
        }
    ],
    "code16.sharp.list": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.list.filters.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        }
    ],
    "code16.sharp.single-show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.download.show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.show.show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.show.delete": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.form.create": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.form.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.form.edit": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.form.update": [
        {
            "name": "globalFilter"
        },
        {
            "name": "parentUri",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.filters.update": [
        {
            "name": "globalFilter"
        }
    ],
    "code16.sharp.update-assets": [],
    "code16.sharp.api.dashboard.command.form": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        }
    ],
    "code16.sharp.api.dashboard.command": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        }
    ],
    "code16.sharp.api.list.command.quick-creation-form.create": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "formEntityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.api.list.command.quick-creation-form.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "formEntityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.api.list": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.api.list.filters.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        }
    ],
    "code16.sharp.api.list.reorder": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        }
    ],
    "code16.sharp.api.list.delete": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.list.state": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.list.command.entity": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        }
    ],
    "code16.sharp.api.list.command.entity.form": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        }
    ],
    "code16.sharp.api.list.command.instance": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.list.command.instance.form": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.dashboard": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.api.dashboard.filters.store": [
        {
            "name": "globalFilter"
        },
        {
            "name": "dashboardKey",
            "required": true
        }
    ],
    "code16.sharp.api.show.command.instance": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.api.show.command.instance.form": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.show.command.singleInstance.form": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "commandKey",
            "required": true
        }
    ],
    "code16.sharp.api.show.state": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.api.search.index": [
        {
            "name": "globalFilter"
        }
    ],
    "code16.sharp.api.embed.form.show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "embedKey",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true
        }
    ],
    "code16.sharp.api.embed.form.update": [
        {
            "name": "globalFilter"
        },
        {
            "name": "embedKey",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true
        }
    ],
    "code16.sharp.api.embed.instance.form.show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "embedKey",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.embed.instance.form.update": [
        {
            "name": "globalFilter"
        },
        {
            "name": "embedKey",
            "required": true
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": true
        }
    ],
    "code16.sharp.api.form.editor.upload.form.update": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.api.form.upload.thumbnail.show": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true
        },
        {
            "name": "instanceId",
            "required": false
        }
    ],
    "code16.sharp.api.form.upload": [],
    "code16.sharp.api.form.autocomplete.index": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "autocompleteFieldKey",
            "required": true
        }
    ],
    "code16.sharp.api.form.refresh.update": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        }
    ],
    "code16.sharp.api.filters.autocomplete.index": [
        {
            "name": "globalFilter"
        },
        {
            "name": "entityKey",
            "required": true,
            "binding": "key"
        },
        {
            "name": "filterHandlerKey",
            "required": true
        }
    ],
    "code16.sharp.login": [],
    "code16.sharp.login.post": [],
    "code16.sharp.login.2fa": [],
    "code16.sharp.login.2fa.post": [],
    "code16.sharp.logout": [],
    "code16.sharp.password.request": [],
    "code16.sharp.password.request.post": [],
    "code16.sharp.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "code16.sharp.password.reset.post": [],
    "code16.sharp.impersonate": [],
    "code16.sharp.impersonate.post": []
}
}
export {};
