/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "code16.sharp.home": [],
    "code16.sharp.dashboard": [
        {
            "name": "dashboardKey"
        }
    ],
    "code16.sharp.list": [
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.single-show": [
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.download.show": [
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.show.show": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.show.delete": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.form.create": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.form.store": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.form.edit": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.form.update": [
        {
            "name": "uri"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.filters.update": [
        {
            "name": "filterKey"
        }
    ],
    "code16.sharp.api.dashboard.command.form": [
        {
            "name": "dashboardKey"
        },
        {
            "name": "commandKey"
        }
    ],
    "code16.sharp.api.dashboard.command": [
        {
            "name": "dashboardKey"
        },
        {
            "name": "commandKey"
        }
    ],
    "code16.sharp.api.list": [
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.api.list.reorder": [
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.api.list.delete": [
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.list.state": [
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.list.command.entity": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        }
    ],
    "code16.sharp.api.list.command.entity.form": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        }
    ],
    "code16.sharp.api.list.command.instance": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.list.command.instance.form": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.show.command.instance": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.show.command.instance.form": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.show.command.singleInstance.form": [
        {
            "name": "entityKey"
        },
        {
            "name": "commandKey"
        }
    ],
    "code16.sharp.api.show.state": [
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.search.index": [],
    "code16.sharp.api.files.show": [
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.embed.show": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.api.embed.form.show": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.api.embed.form.update": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        }
    ],
    "code16.sharp.api.embed.instance.show": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.embed.instance.form.show": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.embed.instance.form.update": [
        {
            "name": "embedKey"
        },
        {
            "name": "entityKey"
        },
        {
            "name": "instanceId"
        }
    ],
    "code16.sharp.api.form.upload": [],
    "code16.sharp.login": [],
    "code16.sharp.login.post": [],
    "code16.sharp.login.2fa": [],
    "code16.sharp.login.2fa.post": [],
    "code16.sharp.logout": [],
    "code16.sharp.password.request": [],
    "code16.sharp.password.request.post": [],
    "code16.sharp.password.reset": [
        {
            "name": "token"
        }
    ],
    "code16.sharp.password.reset.post": []
}
}
export {};
