name: Deploy
on:
  push:
    tags:
    - 'v9.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ping forge to start deploy
        run: curl https://forge.laravel.com/servers/503638/sites/1462752/deploy/http?token=${{ secrets.FORGE_DEPLOY_TOKEN }}
