name: Deploy
on:
  workflow_dispatch:
  push:
    tags:
    - 'v9.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ping forge to start deploy
        run: |
          for url in $FORGE_DEPLOY_URLS; do
            echo "Pinging $url..."
            curl "$url"
          done
        env:
          FORGE_DEPLOY_URLS: ${{ secrets.FORGE_DEPLOY_URLS }}
