name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (X.X.X)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release ${{ inputs.version }}

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.5

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Remove optional "v" prefix
        id: version
        run: |
          echo "version=${VERSION#v}" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ inputs.version }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Build assets
        run: npm run build

      - name: Commit assets
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "Assets"
          file_pattern: dist

      - name: Update SharpInternalServiceProvider.php version
        run: sed -i "s/const VERSION = '.*';/const VERSION = '${{ steps.version.outputs.version }}';/g" src/SharpInternalServiceProvider.php

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "Update version to v${{ steps.version.outputs.version }}"
          file_pattern: src/SharpInternalServiceProvider.php
          tagging_message: "v${{ steps.version.outputs.version }}"
  deploy:
    needs: release
    uses: code16/sharp/.github/workflows/deploy.yml@9.x
    secrets: inherit
