name: Send Discord Release message
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Discord Release message
        uses: SethCohen/github-releases-to-discord@v1
        with:
          username: "Sharp"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: '3447003'
